name: JSON file validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main  

jobs:
  validate-json:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file:
          - $(find . -type f -name 'assessment.json')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate JSON files
        uses: cardinalby/schema-validator-action@v3
        with:
          file: ${{ matrix.file }}
          schema: 'schemas/assessment.schema.json'
          refSchemasMap: '{"https://github.com/ASSERT-KTH/lollm//blob/main/schemas/assessment.schema.json": "schemas/assessment.schema.json"}'
