name: JSON file validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main  

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Validate JSON files
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'data/**/assessment.json' 
          schema: 'schemas/assessment.schema.json'
